#ifndef LIB_QUENTIER_NOTE_EDITOR_SETTINGS_NAME_H
#define LIB_QUENTIER_NOTE_EDITOR_SETTINGS_NAME_H

#define NOTE_EDITOR_SETTINGS_NAME QStringLiteral("NoteEditor")

#endif // LIB_QUENTIER_NOTE_EDITOR_SETTINGS_NAME_H
