message(STATUS "Looking for system wide installation of QsLog")
find_path(QSLOG_INCLUDE_PATH QsLog.h SILENT REQUIRED)
if(NOT QSLOG_INCLUDE_PATH)
  message(FATAL_ERROR "Can't find development header QsLog.h")
elseif(NOT EXISTS ${QSLOG_INCLUDE_PATH}/QsLogLevel.h)
  message(FATAL_ERROR "Found path to QsLog.h in ${QSLOG_INCLUDE_PATH} but can't find QsLogLevel.h in the same folder")
elseif(NOT EXISTS ${QSLOG_INCLUDE_PATH}/QsLogDisableForThisFile.h)
  message(FATAL_ERROR "Found path to QsLog.h in ${QSLOG_INCLUDE_PATH} but can't find QsLogDisableForThisFile.h in the same folder")
elseif(NOT EXISTS ${QSLOG_INCLUDE_PATH}/QsLogDest.h)
  message(FATAL_ERROR "Found path to QsLog.h in ${QSLOG_INCLUDE_PATH} but can't find QsLogDest.h in the same folder")
elseif(NOT EXISTS ${QSLOG_INCLUDE_PATH}/QsLogDestFunctor.h)
  message(FATAL_ERROR "Found path to QsLog.h in ${QSLOG_INCLUDE_PATH} but can't find QsLogDestFunctor.h in the same folder")
elseif(NOT EXISTS ${QSLOG_INCLUDE_PATH}/QsLogDestFile.h)
  message(FATAL_ERROR "Found path to QsLog.h in ${QSLOG_INCLUDE_PATH} but can't find QsLogDestFile.h in the same folder")
elseif(NOT EXISTS ${QSLOG_INCLUDE_PATH}/QsLogDestConsole.h)
  message(FATAL_ERROR "Found path to QsLog.h in ${QSLOG_INCLUDE_PATH} but can't find QsLogDestConsole.h in the same folder")
else()
  message(STATUS "Found development headers for QsLog in folder ${QSLOG_INCLUDE_PATH}")
  find_library(QSLOG_LIB
               NAMES libQsLog.so libQsLog.a libQsLog.dylib libQsLog.dll QsLog.dll libQsLog.lib QsLog.lib
               SILENT REQUIRED)
  if(NOT QSLOG_LIB)
    message(FATAL_ERROR "Can't find QsLog library")
  else()
    message(STATUS "Found QsLog library: ${QSLOG_LIB}")
  endif()
endif()
