// File menu
PROCESS_ACTION_SHORTCUT(NewNote, QKeySequence::New);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(NewNotebook);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(NewTag);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(NewSavedSearch);
PROCESS_ACTION_SHORTCUT(Print, QKeySequence::Print);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(BackupCopy);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(RestoreDatabase);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(ClearTrash);
PROCESS_ACTION_SHORTCUT(Quit, QKeySequence::Quit);

// Edit menu
PROCESS_ACTION_SHORTCUT(Undo, QKeySequence::Undo);
PROCESS_ACTION_SHORTCUT(Redo, QKeySequence::Redo);
PROCESS_ACTION_SHORTCUT(Cut, QKeySequence::Cut);
PROCESS_ACTION_SHORTCUT(Copy, QKeySequence::Copy);
PROCESS_ACTION_SHORTCUT(Paste, QKeySequence::Paste);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(PasteUnformatted);
PROCESS_ACTION_SHORTCUT(SelectAll, QKeySequence::SelectAll);
PROCESS_ACTION_SHORTCUT(Delete, QKeySequence::Delete);

// Find and replace menu
PROCESS_NON_STANDARD_ACTION_SHORTCUT(FindNote);
PROCESS_ACTION_SHORTCUT(FindInsideNote, QKeySequence::Find);
PROCESS_ACTION_SHORTCUT(FindNext, QKeySequence::FindNext);
PROCESS_ACTION_SHORTCUT(FindPrevious, QKeySequence::FindPrevious);
PROCESS_ACTION_SHORTCUT(ReplaceInNote, QKeySequence::Replace);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(SpellCheck);

// View menu
PROCESS_NON_STANDARD_ACTION_SHORTCUT(Notes, "View");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(Notebooks, "View");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(Tags, "View");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(SavedSearches, "View");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(ShowSidePanel, "View");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(ShowFavorites, "View");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(ShowNotes, "View");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(ShowNotebooks, "View");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(ShowTags, "View");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(ShowSavedSearches, "View");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(ShowTrash, "View");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(ShowNotesList, "View");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(ShowNoteEditor, "View");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(ShowToolbar, "View");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(ShowStatusBar, "View");

// Format menu
PROCESS_ACTION_SHORTCUT(FontBold, QKeySequence::Bold);
PROCESS_ACTION_SHORTCUT(FontUnderlined, QKeySequence::Underline);
PROCESS_ACTION_SHORTCUT(FontItalic, QKeySequence::Italic);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(FontStrikethrough);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(FontHighlight);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(FontUpperIndex);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(FontLowerIndex);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(IncreaseFontSize);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(DecreaseFontSize);
PROCESS_ACTION_SHORTCUT(InsertHorizontalLine, QKeySequence::InsertLineSeparator);

PROCESS_NON_STANDARD_ACTION_SHORTCUT(InsertTable, "Table");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(InsertRow, "Table");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(InsertColumn, "Table");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(RemoveRow, "Table");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(RemoveColumn, "Table");

PROCESS_NON_STANDARD_ACTION_SHORTCUT(SaveImage, "Image");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(RotateClockwise, "Image");
PROCESS_NON_STANDARD_ACTION_SHORTCUT(RotateCounterClockwise, "Image");

PROCESS_NON_STANDARD_ACTION_SHORTCUT(AlignLeft);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(AlignCenter);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(AlignRight);

PROCESS_NON_STANDARD_ACTION_SHORTCUT(InsertBulletedList);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(InsertNumberedList);

PROCESS_NON_STANDARD_ACTION_SHORTCUT(IncreaseIndentation);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(DecreaseIndentation);

// Service menu
PROCESS_NON_STANDARD_ACTION_SHORTCUT(Synchronize);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(AccountInfo);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(LocalDatabaseStatus);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(ImportFolders);
PROCESS_ACTION_SHORTCUT(Preferences, QKeySequence::Preferences);

// Help menu
PROCESS_NON_STANDARD_ACTION_SHORTCUT(ReleaseNotes);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(ViewLogs);
PROCESS_NON_STANDARD_ACTION_SHORTCUT(About);
