macro(update_translation SOURCES FORMS TRANSLATIONS)
  # First generate the fake .pro file for lupdate utility
  set(fake_pro_file "${PROJECT_BINARY_DIR}/fake_pro_file.pro")

  # generate .pro file for lupdate utility
  file(WRITE "${fake_pro_file}"
    "#\n"
    "# This file was autogenerated by update_translation macro\n"
    "# All changes will be lost\n"
    "#\n")

  # SOURCES section
  file(APPEND "${fake_pro_file}"
    "\n"
    "SOURCES =\\\n")

  foreach(source_file ${SOURCES})
    file(APPEND "${fake_pro_file}" "  ${PROJECT_SOURCE_DIR}/${source_file}\\\n")
  endforeach()

  # FORMS section
  file(APPEND "${fake_pro_file}"
    "\n"
    "FORMS =\\\n")

  foreach(form_file ${FORMS})
    file(APPEND "${fake_pro_file}" "  ${PROJECT_SOURCE_DIR}/${form_file}\\\n")
  endforeach()

  # TRANSLATIONS section
  file(APPEND "${fake_pro_file}"
    "\n"
    "TRANSLATIONS =\\\n")

  foreach(translation_file ${TRANSLATIONS})
    file(APPEND "${fake_pro_file}" "  ${PROJECT_SOURCE_DIR}/${translation_file}\\\n")
  endforeach()

  if(USE_QT5)
    set(LUPDATE ${Qt5Core_DIR}/../../../bin/lupdate)
    set(LRELEASE ${Qt5Core_DIR}/../../../bin/lrelease)
  else()
    get_filename_component(QT_BIN_DIR ${QT_QMAKE_EXECUTABLE} PATH)
    set(LUPDATE ${QT_BIN_DIR}/lupdate)
    set(LRELEASE ${QT_BIN_DIR}/lrelease)
  endif()

  add_custom_target(lupdate COMMAND ${LUPDATE} -verbose \"${fake_pro_file}\" DEPENDS ${fake_pro_file})

  add_custom_target(lrelease)
  file(MAKE_DIRECTORY "${PROJECT_BINARY_DIR}/translations")
  foreach(translation_file ${TRANSLATIONS})
    string(LENGTH ${translation_file} TR_FILE_LEN)
    string(FIND ${translation_file} "_" BEGIN_POS REVERSE)
    math(EXPR BEGIN_POS "${BEGIN_POS}+1")
    string(FIND ${translation_file} "." END_POS REVERSE)
    math(EXPR LANG_CODE_LEN "${END_POS}-${BEGIN_POS}")
    string(SUBSTRING ${translation_file} ${BEGIN_POS} ${LANG_CODE_LEN} LANG_CODE)
    set(QM_FILE "${PROJECT_BINARY_DIR}/translations/quentier_${LANG_CODE}.qm")
    list(APPEND ${PROJECT_NAME}_QM_FILES ${QM_FILE})
    add_custom_command(COMMAND ${LRELEASE} \"${PROJECT_SOURCE_DIR}/${translation_file}\" -qm \"${QM_FILE}\" TARGET lrelease)
  endforeach()
endmacro()
